select FIRST_NAME, LAST_NAME, EMAIL, USERNAME, EMAIL_VERIFIED, U.ID as ID,
C.SECRET_DATA::jsonb ->> 'value' as PASSWORD,
C.SECRET_DATA::jsonb ->> 'salt' as SALT,
C.CREDENTIAL_DATA::jsonb ->> 'hashIterations' as HASHITERATIONS,
C.CREDENTIAL_DATA::jsonb ->> 'algorithm' as ALGORITHM,
CREATED_TIMESTAMP, REALM_ID
from USER_ENTITY U, CREDENTIAL C
where U.ID = C.USER_ID AND U.REALM_ID = 'RealmID'
