[
  {
    name: "id",
    type: "id",
    description: "simple identifier for this entity",
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "uuid",
    type: "uuid",
    description: "globally unique identifier for this entity",
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "created",
    type: "dateTime",
    description: "when this entity was created",
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "lastUpdated",
    type: "dateTime",
    description: "when this entity was last updated",
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "accountDataRequestTime",
    type: "dateTime",
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "accountDeleteRequestTime",
    type: "dateTime",
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "birthday",
    type: "date",
    description: "End-User's birthday. Returned by the `birthdate` claim.",
    "locally-unique": false,
    query: true,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "clients",
    type: "plural",
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "clients.id",
    type: "id",
    description: "simple identifier for this sub-entity",
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "clients.clientId",
    type: "string",
    "case-sensitive": true,
    "locally-unique": true,
    query: false,
    required: true,
    "primary-key": true,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "clients.firstLogin",
    type: "dateTime",
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "clients.lastLogin",
    type: "dateTime",
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "clients.name",
    type: "string",
    "case-sensitive": false,
    length: 1000,
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "consents",
    type: "object",
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "consents.marketing",
    type: "object",
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "consents.marketing.clientId",
    type: "string",
    "case-sensitive": true,
    description: "Client ID used to modify the consent.",
    length: 32,
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "consents.marketing.context",
    type: "string",
    "case-sensitive": true,
    description: "Context in which the consent was changed.",
    length: 100,
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "consents.marketing.granted",
    type: "boolean",
    description: "Whether or not the consent is granted.",
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "consents.marketing.oidcClientId",
    type: "string",
    "case-sensitive": true,
    description: "OIDC Client ID used to modify the consent.",
    length: 36,
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "consents.marketing.type",
    type: "string",
    "case-sensitive": true,
    description: "Type of consent, 'implicit' or 'explicit'.",
    length: 8,
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "consents.marketing.updated",
    type: "dateTime",
    description: "Date and time of the last change to the consent.",
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "deactivateAccount",
    type: "dateTime",
    description: "Time when the account was deactivated.",
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "display",
    type: "json",
    description:
      "Placeholder for public data. Referenced as 'public_display' in the flow.",
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "displayName",
    type: "string",
    "case-sensitive": false,
    description:
      "Shorthand name by which the End-User wishes to be referred to at the RP, such as janedoe or j.doe. Returned by the `preferred_username` claim.",
    length: 1000,
    "locally-unique": false,
    query: true,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "email",
    type: "string",
    "case-sensitive": false,
    description:
      "End-User's preferred e-mail address. Returned by the `email` claim.",
    length: 256,
    "locally-unique": false,
    query: true,
    required: false,
    "primary-key": false,
    "reverse-query": true,
    unique: true,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "emailVerified",
    type: "dateTime",
    description:
      "Time when the email address was verified. Returned as boolean by the `email_verified` claim.",
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "externalId",
    type: "string",
    "case-sensitive": false,
    length: 1000,
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "familyName",
    type: "string",
    "case-sensitive": false,
    description:
      "Surname(s) or last name(s) of the End-User. Returned by the `family_name` claim.",
    length: 1000,
    "locally-unique": false,
    query: true,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "fullName",
    type: "string",
    "case-sensitive": false,
    description:
      "End-User's full name in displayable form including all name parts, possibly including titles and suffixes, ordered according to the End-User's locale and preferences. Returned by the `name` claim.",
    length: 1000,
    "locally-unique": false,
    query: true,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "gender",
    type: "string",
    "case-sensitive": false,
    description: "End-User's gender. Returned by the `gender` claim.",
    length: 100,
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "givenName",
    type: "string",
    "case-sensitive": false,
    description:
      "Given name(s) or first name(s) of the End-User. Returned by the `given_name` claim.",
    length: 1000,
    "locally-unique": false,
    query: true,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "lastLogin",
    type: "dateTime",
    description: "Time of the last authentication.",
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "legalAcceptances",
    type: "plural",
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "legalAcceptances.id",
    type: "id",
    description: "simple identifier for this sub-entity",
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "legalAcceptances.clientId",
    type: "string",
    "case-sensitive": true,
    length: 32,
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "legalAcceptances.dateAccepted",
    type: "dateTime",
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "legalAcceptances.legalAcceptanceId",
    type: "string",
    "case-sensitive": false,
    length: 1000,
    "locally-unique": true,
    query: false,
    required: true,
    "primary-key": true,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "middleName",
    type: "string",
    "case-sensitive": false,
    description:
      "Middle name(s) of the End-User. Returned by the `middle_name` claim.",
    length: 1000,
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "mobileNumber",
    type: "string",
    "case-sensitive": false,
    length: 256,
    "locally-unique": false,
    query: true,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: true,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "mobileNumberVerified",
    type: "dateTime",
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "password",
    type: "password-bcrypt",
    description: "End-User's password.",
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "photos",
    type: "plural",
    description: "Primary user profile photos.",
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "photos.id",
    type: "id",
    description: "simple identifier for this sub-entity",
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "photos.type",
    type: "string",
    "case-sensitive": true,
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "photos.value",
    type: "string",
    "case-sensitive": true,
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "primaryAddress",
    type: "object",
    description:
      "End-User's preferred postal address. Returned by the `address` claim.",
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "primaryAddress.address1",
    type: "string",
    "case-sensitive": false,
    length: 1000,
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "primaryAddress.address2",
    type: "string",
    "case-sensitive": false,
    length: 1000,
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "primaryAddress.city",
    type: "string",
    "case-sensitive": false,
    length: 1000,
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "primaryAddress.company",
    type: "string",
    "case-sensitive": false,
    length: 1000,
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "primaryAddress.country",
    type: "string",
    "case-sensitive": false,
    length: 1000,
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "primaryAddress.phone",
    type: "string",
    "case-sensitive": false,
    length: 100,
    "locally-unique": false,
    query: true,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "primaryAddress.stateAbbreviation",
    type: "string",
    "case-sensitive": false,
    length: 100,
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "primaryAddress.zip",
    type: "string",
    "case-sensitive": false,
    length: 100,
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "primaryAddress.zipPlus4",
    type: "string",
    "case-sensitive": false,
    length: 100,
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "profiles",
    type: "plural",
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "profiles.id",
    type: "id",
    description: "simple identifier for this sub-entity",
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "profiles.domain",
    type: "string",
    "case-sensitive": false,
    length: 1000,
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "profiles.identifier",
    type: "string",
    "case-sensitive": false,
    description: "Profile provider unique identifier",
    length: 1000,
    "locally-unique": false,
    query: false,
    required: true,
    "primary-key": false,
    "reverse-query": false,
    unique: true,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "profiles.photo",
    type: "string",
    "case-sensitive": true,
    description: "URL of a photo of this contact.",
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "profiles.providerSpecifier",
    type: "string",
    "case-sensitive": true,
    description:
      "Internal text field for identifying the provider in a unique and normalized manner.",
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "roles",
    type: "plural",
    description:
      "A list of roles for the User that collectively represent who the User is, e.g., 'Student', 'Faculty'.",
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "roles.id",
    type: "id",
    description: "simple identifier for this sub-entity",
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "roles.display",
    type: "string",
    "case-sensitive": true,
    description: "A human-readable name, primarily used for display purposes.",
    length: 1000,
    "locally-unique": false,
    query: false,
    required: false,
    "primary-key": false,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
  {
    name: "roles.value",
    type: "string",
    "case-sensitive": false,
    description: "The value of a role.",
    length: 256,
    "locally-unique": true,
    query: false,
    required: true,
    "primary-key": true,
    "reverse-query": false,
    unique: false,
    "to-upper": false,
    "to-lower": false,
    "ignore-update": false,
  },
];
